import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { SupabaseService } from '../../core/supabase.service';

@Component({ selector: 'app-login', imports: [ReactiveFormsModule, RouterLink], template: `
<main><a routerLink="/" class="back">← Volver al sitio</a><section><div class="mark">INXHINIE <small>CONSTRUCCIONES</small></div><h1>Acceso administrativo</h1><p>Ingresa con la cuenta autorizada por la empresa.</p>@if (!supabase.configured) {<div class="notice"><strong>Configuración pendiente</strong><span>Agrega las credenciales de Supabase en <code>src/app/core/environment.ts</code> y crea un usuario en Supabase Auth.</span></div>}<form [formGroup]="form" (ngSubmit)="submit()"><label>Correo electrónico<input type="email" formControlName="email" autocomplete="email"></label><label>Contraseña<input type="password" formControlName="password" autocomplete="current-password"></label>@if (error()) {<p class="error">{{ error() }}</p>}<button type="submit" [disabled]="loading()">{{ loading() ? 'Validando...' : 'Ingresar' }}</button></form></section></main>`, styles: `:host{display:block;min-height:100dvh;background:#090b0d;color:#f3f1e9}main{max-width:1100px;margin:auto;padding:34px 24px}.back{color:#d6b758;text-decoration:none;font-size:14px}section{max-width:440px;margin:12vh auto 0;padding:38px;background:#121617;border:1px solid #ffffff1c}.mark{color:#e5c96e;font-weight:800;letter-spacing:.14em}.mark small{display:block;font-size:8px;letter-spacing:.2em;color:#a7a79f}h1{margin:28px 0 8px;font-size:38px;letter-spacing:-.05em}p{color:#afb0a9;line-height:1.6}.notice{display:flex;flex-direction:column;gap:6px;padding:14px;margin:22px 0;background:#d6b75812;border-left:2px solid #d6b758;color:#d0d0ca;font-size:13px}.notice strong{color:#e5c96e}.notice code{color:#f4f0df}form{display:grid;gap:18px;margin-top:26px}label{display:grid;gap:7px;font-size:13px;font-weight:bold}input{background:#090b0d;border:1px solid #ffffff25;color:#f4f2eb;padding:12px;border-radius:3px}input:focus{outline:2px solid #d6b758}button{border:0;background:#d6b758;color:#171711;padding:13px;font-weight:bold;cursor:pointer;border-radius:3px}button:disabled{opacity:.6}.error{color:#f3aaa2;margin:0;font-size:13px}` })
export class LoginComponent {
  readonly supabase = inject(SupabaseService); private readonly fb = inject(FormBuilder); private readonly router = inject(Router);
  readonly loading = signal(false); readonly error = signal('');
  readonly form = this.fb.group({ email: ['', [Validators.required, Validators.email]], password: ['', Validators.required] });
  async submit() { if (this.form.invalid) { this.form.markAllAsTouched(); return; } this.loading.set(true); this.error.set(''); const result = await this.supabase.signIn(this.form.value.email!, this.form.value.password!); this.loading.set(false); if (result.error) { this.error.set(result.error.message); return; } await this.router.navigateByUrl('/admin'); }
}
